name: foliokit-development

services:
  mongodb:
    image: mongo:7.0
    container_name: foliokit-mongodb
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.adminCommand('ping').ok"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build:
      context: .
      dockerfile: server/Dockerfile

    image: foliokit-server:development
    container_name: foliokit-server
    restart: unless-stopped

    env_file:
      - ./server/.env.development

    expose:
      - "5000"

    depends_on:
      - mongodb:
          condition: service_healthy

    networks:
      - backend

  client:
    build:
      context: .
      dockerfile: client/Dockerfile

    image: foliokit-client:development
    container_name: foliokit-client
    restart: unless-stopped

    env_file:
      - ./client/.env.development

    expose:
      - "5173"

    depends_on:
      - server

    networks:
      - frontend

  nginx:
    image: nginx:1.27-alpine
    container_name: foliokit-nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - client
      - server

    networks:
      - frontend
      - backend


volumes:
  mongodb_development_data:


networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge