version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: foliokit-mongo-container
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - foliokit-mongo-data:/data/db
    networks:
      - foliokit-network
    
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: foliokit-api-container
    env_file:
      - ./server/.env.development
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - foliokit-network
    depends_on:
      - mongo

volumes:
  foliokit-mongo-data:

networks:
  foliokit-network:
    driver: bridge

    